# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: cyberthreatinfo
google_analytics: UA-6168771-2
title: Cyber Threat

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: cyberthreatinfo

description: Stylish Jekyll Theme
author:
  name: cyberthreatinfo
  #email: cyberthreatinfo@ismaildemirbilek.com
  #github: cyberthreatinfo
  twitter: cyberthreatinfo
  #pinterest: asd123
  linkedin1: rod-lewis-919b441
  linkedin2: russell-chan-cissp-7030471/
  bio: Experts Musing on Cyber Security!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: 
BASE_PATH_rss: https://www.cyberthreat.info

plugins:
  - jekyll-paginate

authors:
  rchan:
    display_name: Russ Chan
    linkedin: https://www.linkedin.com/in/russell-chan-cissp-7030471/
    isc2: https://www.youracclaim.com/badges/64dc456b-a99a-4319-a875-49fe66c3576b
  rlewis:
    display_name: Rod Lewis
    linkedin: https://www.linkedin.com/in/rod-lewis-919b441/
    isc2: https://www.youracclaim.com/badges/d1c1efe4-bdd0-4e06-818a-817ea13d0a7e/public_url
